name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'  
    - name: Update apt cache
      run: sudo apt-get update
    - name: Install prereq
      run: sudo apt-get install libxml2-utils
    - name: Graylog version
      id: vinfo
      run: |
        export GRAYLOG_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="parent"]/*[local-name()="version"]/text()' pom.xml)
        echo "Building for Graylog ${GRAYLOG_VERSION}"
        echo "GRAYLOG_VERSION=${GRAYLOG_VERSION}" >> $GITHUB_ENV
        echo "::set-output name=GRAYLOG_VERSION::$GRAYLOG_VERSION"
        echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
    - uses: actions/cache@v3
      id: cache
      with:
        path: /home/runner/work/TelegramAlert/graylog2-server
        key: ${{ runner.os }}-${{ steps.vinfo.outputs.date }}-${{ steps.vinfo.outputs.GRAYLOG_VERSION }}
    - name: Initialize Graylog
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        echo "Checking out Graylog ${{ env.GRAYLOG_VERSION }}"
        git clone --depth 1 --branch "${{ env.GRAYLOG_VERSION }}" https://github.com/Graylog2/graylog2-server.git ../graylog2-server
        pushd ../graylog2-server
        mvn generate-resources -pl graylog2-server -B -V
        pushd graylog2-web-interface
        yarn install
        env disable_plugins=true ./node_modules/.bin/webpack --config webpack.vendor.js
        popd; popd
    - name: Missing deps
      run: npm install react-bootstrap-validation --save
    - name: Build
      run: mvn -B package --file pom.xml
    - name: Package deb
      if: startsWith(github.ref, 'refs/tags/v')
      run: mvn jdeb:jdeb
    - name: Package rpm
      if: startsWith(github.ref, 'refs/tags/v')
      run: mvn rpm:rpm
    - name: Cleanup
      if: startsWith(github.ref, 'refs/tags/v')
      run: rm -f target/original-*.jar